### PR TITLE
Upgrade to node-sass 2.0.1

### PR DESCRIPTION
**Pull request by jasonsanjose**
* Upgrade to node-sass 2.0.1 https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-101
    * Update README instructions for compiling mac 32-bit binary
* Allow ruby compiler warnings
* Experimental compass support
* Fix errors for partials #87

Changes to .brackets.json settings
```
{
    {
       "sass.compiler": "libsass|ruby", // default: "libsass"
       "sass.compass": false // default: false, experimental compile-only support (no live preview). requires config.rb at project root
    },
    "path": {
        "path/to/my.scss": {
            "sass.options": {
                "sourceMap": true | "relative/path/from/input.css.map" // default: true
            }
        }
    }
}
```

### CODE REVIEW

**Comment by jasonsanjose** [comment]
@nicolo-ribaudo Do you have time to help me test this update?

**Comment by nicolo-ribaudo** [comment]
Yes, is there any special case to test?

**Comment by jasonsanjose** [comment]
General workflows. I'm seeing some issues with the grunt build currently. I'll let you know when I can post a zip.

**Comment by jasonsanjose** [comment]
Here's the zip build https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-91

**Comment by nicolo-ribaudo** [comment]
Can I just clone the jasonsanjose/v2 branch or the zip build may have some other issues?

**Comment by jasonsanjose** [comment]
Try the zip to make sure that the node dependencies are getting included correctly.

**Comment by nicolo-ribaudo** [comment]
Ok, I installed the zip.

---

If `.scss` and `.css` files are in different folders, live preview doesn't update until I save the scss file.

https://github.com/nicolo-ribaudo/brackets-sass-tests/tree/live-preview-different-paths/

**Comment by jasonsanjose** [comment]
Thanks. I'll take a look. I haven't tested on windows yet.

**Comment by nicolo-ribaudo** [comment]
I'll try to fix the error thrown while using Ruby this weekend.

**Comment by nicolo-ribaudo** [comment]
Seems fixed.
But css files aren't generated if the project isn't on `c:/` and a partial is imported.

**Comment by jasonsanjose** [comment]
>Seems fixed.
But css files aren't generated if the project isn't on c:/ and a partial is imported.

Are you talking about your fix in this other PR #99?

**Comment by jasonsanjose** [comment]
@nicolo-ribaudo I updated the build here https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-101.

I just added basic compass support for compiling on save only, no live preview support yet. I think this is good enough to call experimental. I posted an example project here https://github.com/jasonsanjose/compass-example.

I think I've finally ironed out all the windows path problems during live preview and on save for both ruby and libsass. Feel free to use the https://github.com/jasonsanjose/bourbon-example project to test compiling and live preview in both the main file and partial file.

**Comment by jasonsanjose** [comment]
Merging this now thanks to some testing from @tijtij and @onetrev. Need to clean up README and post release notes.

**Pull request merged**
